name: mobile
description: "EduFlowAI mobile application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router: ^14.7.0

  # Storage & Persistence
  shared_preferences: ^2.5.0
  flutter_secure_storage: ^9.2.2

  # API & Networking
  dio: ^5.10.0

  # UI & Animation
  animate_do: ^3.3.0
  flutter_animate: ^4.5.2

  # State Management & Utils
  flutter_riverpod: ^2.6.1
  intl: ^0.20.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true